### ISSUE TITLE
maven hook fails

### ISSUE THREAD

**Issue by saravankrish** [ejba/pre-commit-maven#5]
Hi,

**_Maven_** hook is failing. Can you please help me resolve this?

Traceback (most recent call last):
  File "/Users/****/.cache/pre-commit/repomy5pvoj0/py_env-python3.9/bin/maven", line 8, in <module>
    sys.exit(main())
TypeError: main() missing 1 required positional argument: 'argv'

Here is my pre-commit-config:

- repo: https://github.com/ejba/pre-commit-maven
  rev: v0.3.0
  hooks:
    - id: maven
      args: ['clean compile -s settings.xml']

**Comment by ejba** [comment]
Sure, give me a moment. It looks like a defect.

**Comment by ejba** [comment]
The release v0.3.1 should fix this problem.
