### ISSUE TITLE
maven-checkstyle hook missing

### ISSUE THREAD

**Issue by dome91** [ejba/pre-commit-maven#6]
Since we updated to v0.3.1, precommit complains that the maven-checkstyle hook is missing.
Was it accidentally removed or was this a conscious decision?

**Comment by ejba** [comment]
It was accident.
 
Thanks for reporting it.

**Comment by ejba** [comment]
I did a new release, v0.3.2, to include the missing hook. Thanks once again.

**Comment by dome91** [comment]
Thank you very much for the quick response!
But are you sure you included the hook in the newest release? Still having the problem with v0.3.2. There also seems that nothing was committed between release v0.3.1 and v0.3.2

**Comment by ejba** [comment]
Yes, you are right. My bad.

**Comment by ejba** [comment]
@Dome91 Do you still have the problem?

**Comment by dome91** [comment]
After executing pre-commit clean and pre-commit install, everything works fine again. Thank you for solving this issue so quickly!

**Comment by ejba** [comment]
I am the one that has to say thanks here for reporting the issue! :)
